### PR TITLE
Fix useless exact match & unshowable subject details

### LINKED ISSUE #86: Close but no cigar & disable partial answer match
Currently it's not possible to turn off the partial matching of answers (there is an option to disable cheating but i still want to have the ignore option).

My ideal would be behaviour like the "close but no cigar" user script, where a partial correct answer notifies you that you are close, but doesn't accept the answer yet and waits for the 100% correct match.

### LINKED ISSUE #172: Emulating Wanikani behavior on wrong answer
When you get a review wrong for a meaning/reading, Wanikani’s webapp only shows you the correct answer for the half you got wrong.

This is good because you don’t see e.g the meaning if you got the reading wrong.

This is an issue with typos — sometimes i might make a typo, mark it as correct, and see the other field before having completed that half of the review. 

Ideally, Tsurukame would only show you the part you got wrong, and let you tap to view the full page.

### LINKED ISSUE #463: Meaning/Reading are randomly not shown
2054A130-1C8C-4EB1-BC77-A2CB9090E212

Since the last update, occasionally, the reading explanation or the meaning explanation is not being shown. (As it can be seen in the image, only the reading explanation is being displayed)

### PR DESCRIPTION
**Pull request by SafePointerT**
Due to bugs, the exact match setting does nothing, the script to change bundle identifers incorrectly matches the doctypes in the complication property lists, and if you review and get the reading wrong but haven't answered the meaning, or vice versa, there's no way to show the meaning and its explanation.

By fixing these bugs, this PR will resolve #86, resolve #172, and resolve #463.

### CODE REVIEW

File: ios/SubjectDetailsView.swift [hunk 1]
```diff
@@ -326,22 +361,30 @@ class SubjectDetailsView: UITableView, SubjectChipDelegate {
...
       addComponents(subject, title: "Kanji", toModel: model)
 
-      if !isReview || meaningAttempted {
+      if meaningShown {
         model.addSection("Meaning Explanation")
         addFormattedText(subject.vocabulary.meaningExplanation,
                          isHint: false, toModel: model)
       }
-      if !isReview || readingAttempted {
+      if meaningShown, readingShown {
```
Comment (davidsansome) [inline ios/SubjectDetailsView.swift:381]: How come the reading explanation is only shown if both meaningShown and readingShown are true?

If it's intentional can you add a comment to explain why?

**Review by davidsansome — APPROVED** [review]
Looks great - thanks for fixing these!

In future please try to separate each fix into its own pull request. It can get quite confusing to review otherwise!

File: ios/SubjectDetailsView.swift (hunk 1 above)
Comment (SafePointerT) [reply ios/SubjectDetailsView.swift:381]: @davidsansome Yes. The reading explanation usually also spoils the meaning. For example, https://www.wanikani.com/kanji/%E4%B8%80

Comment (davidsansome) [reply ios/SubjectDetailsView.swift:381]: Ah ok makes sense! Could you put that in a `// Comment` above this line to make it clear to the next person to read the code?

Comment (SafePointerT) [reply ios/SubjectDetailsView.swift:382]: @davidsansome Absolutely, just added that!

**Comment by UInt2048** [comment]
> In future please try to separate each fix into its own pull request

I'd like to apologize for this. I realize that I haven't exactly been doing this, and I'd like to fix that. I'm going to mark my unwieldy PRs as draft so that I can split them up. Could you please give me another chance, or tell me if I've assumed incorrectly?

**Comment by davidsansome** [comment]
Yeah that PR is pretty much impossible to review right now :D If you can split each individual change/feature into separate PRs I'll definitely take another look!

**Comment by UInt2048** [comment]
@davidsansome Could you please take a look at #470? It only affects a single line of code.
